### ISSUE TITLE
How to achieve  automatically rectify distorted text images,just like the result showed in the picture

### ISSUE THREAD

**Issue by Lesley96-11** [WarBean/tps_stn_pytorch#2]
Actually I don't understand how to train it , what kind of data should I prepare, and how to rectify distored text images

**Comment by WarBean** [comment]
You do not need to prepare data for running my code, because PyTorch's API already provides data loading functionality. However, if you want to use your own dataset, you should implement your customized dataloader. Please refer to http://pytorch.org/tutorials/beginner/data_loading_tutorial.html.

**Comment by Lesley96-11** [comment]
@WarBean Thanks for your advice.   I want to input a distorted text image ,and the output is a rectified picture. How to achieve it. Can your program achieve that?

**Comment by WarBean** [comment]
Please check this line: https://github.com/WarBean/tps_stn_pytorch/blob/master/mnist_model.py#L102. The variable `transformed_x` is the rectified image. You can modify my code to fetch it out.
