### ISSUE TITLE
How to transform an image to a target shape

### ISSUE THREAD

**Issue by nvnnghia** [WarBean/tps_stn_pytorch#5]
Thanks for sharing your awesome works. I want to transform target clothing to have the shape of clothing mask. How to use this code to do like this:  ![image](https://user-images.githubusercontent.com/31887969/41701358-26e05e88-7567-11e8-8d16-3e53ddff8120.png)

Thanks

**Comment by Zhang-O** [comment]
how much will you pay for the code?
